#[build]
#publish = "dist/pokemon-ssr/browser"
#command = "ng build --configuration=production"
#
#[[redirects]]
#from = "/*"
#to = "/index.html"
#status = 200
#
#[functions]
#node_bundler = "esbuild"
